apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: '2017-12-06T18:14:10Z'
  generation: 42
  labels:
    app: s2i-spring-boot-camel
    component: s2i-spring-boot-camel
    group: quickstarts
    project: s2i-spring-boot-camel
  name: s2i-spring-boot-camel
  namespace: spring-boot-test
spec:
  replicas: 1
  selector:
    component: s2i-spring-boot-camel
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: s2i-spring-boot-camel
        deploymentconfig: s2i-spring-boot-camel
        group: quickstarts
        project: s2i-spring-boot-camel
        provider: s2i
        version: 1.0.0.redhat-000055
    spec:
      containers:
        - env:
            - name: JAVA_ARGS
              value: '--spring.config.location=file:/etc/config/application.properties'
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: >-
            172.30.1.1:5000/spring-boot/s2i-spring-boot-camel@sha256:3cb6ee2ba7c4c59fc911431fdba58be0d78b8584d0c9084c2b80b1d4b746a6f2
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 9081
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: s2i-spring-boot-camel
          ports:
            - containerPort: 8778
              name: jolokia
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 9081
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: '1'
            requests:
              cpu: 200m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/config
              name: config-volume-telco
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: telco-nz
          name: config-volume-telco
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - s2i-spring-boot-camel
        from:
          kind: ImageStreamTag
          name: 's2i-spring-boot-camel:TestReady'
          namespace: spring-boot
        lastTriggeredImage: >-
          172.30.1.1:5000/spring-boot/s2i-spring-boot-camel@sha256:3cb6ee2ba7c4c59fc911431fdba58be0d78b8584d0c9084c2b80b1d4b746a6f2
      type: ImageChange
