apiVersion: v1
kind: ImageStream
metadata:

  labels:
    app: fis-java-openshift
  name: fis-java-openshift
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations:
        openshift.io/generated-by: OpenShiftWebConsole
        openshift.io/imported-from: registry.access.redhat.com/jboss-fuse-6/fis-java-openshift
      from:
        kind: DockerImage
        name: registry.access.redhat.com/jboss-fuse-6/fis-java-openshift
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
